import { FormEvent } from 'react';
import { Head, useForm } from '@inertiajs/react';

export default function RentalProfile({ profile }: { profile: { business_name: string; status: string; rejected_reason: string | null } | null }) {
    const form = useForm({ business_name: '', contact_number: '', email: '', business_address: '', business_registration_file: null as File | null, valid_id_file: null as File | null });
    function submit(event: FormEvent) { event.preventDefault(); form.post('/rental-provider/profile', { forceFormData: true }); }
    return <><Head title="Rental Business Verification" /><div className="mx-auto max-w-2xl p-4"><h1 className="text-2xl font-semibold">Rental Business Verification</h1>{profile && profile.status !== 'rejected' ? <div className="mt-6 rounded-lg border p-5"><p className="font-medium">{profile.business_name}</p><p className="mt-1 text-sm text-muted-foreground">Status: {profile.status.replace('_', ' ')}</p></div> : <form onSubmit={submit} className="mt-6 grid gap-4 rounded-lg border p-5"><input required placeholder="Business name" className="h-10 rounded-md border px-3" value={form.data.business_name} onChange={e => form.setData('business_name', e.target.value)} /><input required placeholder="Contact number" className="h-10 rounded-md border px-3" value={form.data.contact_number} onChange={e => form.setData('contact_number', e.target.value)} /><input type="email" placeholder="Business email" className="h-10 rounded-md border px-3" value={form.data.email} onChange={e => form.setData('email', e.target.value)} /><textarea required placeholder="Business address" className="min-h-24 rounded-md border p-3" value={form.data.business_address} onChange={e => form.setData('business_address', e.target.value)} /><label className="grid gap-2 text-sm">Business registration document<input required type="file" accept="image/jpeg,image/png,application/pdf" onChange={e => form.setData('business_registration_file', e.target.files?.[0] ?? null)} /></label><label className="grid gap-2 text-sm">Owner's valid government ID<input required type="file" accept="image/jpeg,image/png,application/pdf" onChange={e => form.setData('valid_id_file', e.target.files?.[0] ?? null)} /></label>{profile?.rejected_reason && <p className="text-sm text-destructive">{profile.rejected_reason}</p>}<button disabled={form.processing} className="h-10 rounded-md bg-primary px-4 text-primary-foreground">Submit for validation</button></form>}</div></>;
}

RentalProfile.layout = { breadcrumbs: [{ title: 'Rental Verification', href: '/rental-provider/profile' }] };
